### ISSUE TITLE
Adafruit BLE control not working under Linux (ubuntu)

### ISSUE THREAD

**Issue by odbeek** [vdwel/RobotControl#2]
Seems not to be working under ubuntu with bluez 5.37. The Adafruit BLE examples work fine. Connecting to dash establishes OK, but seems to get stuck at self.robotService = btdev.find_service(ROBOT_SERVICE_UUID) in robot.**init**()

I removed the self.btdev.discover() command, here's the console output, running as sudo:

starting example_treading
Using adapter: peter-1215B #1
Connected to  Dash
self.robotService - **this was a print command**
self.commandChar - **this was a print command**
Traceback (most recent call last):
  File "example_threading.py", line 74, in <module>
    ble.run_mainloop_with(main)
  File "build/bdist.linux-x86_64/egg/Adafruit_BluefruitLE/bluez_dbus/provider.py", line 118, in _user_thread_main
  File "example_threading.py", line 69, in main
    dash = robot(getRobotDevice())
  File "/home/peter/dev/Python/dash/robot.py", line 102, in __init__
    self.commandChar = self.robotService.find_characteristic(COMMAND_CHAR_UUID)
AttributeError: 'NoneType' object has no attribute 'find_characteristic'

Still not working after last fix. I'll look into this later

**Comment by jamesrabbitt** [comment]
Experiencing the same issue. Wondering if there is a fix?

**Comment by odbeek** [comment]
No fix. It's bin a while but I used https://github.com/IlyaSukhanov/morseapi instead. Works reasonable well considering it uses gatttool

**Comment by jamesrabbitt** [comment]
I've had trouble getting MorseAPI working on my Pi3 - any tips?

**Comment by odbeek** [comment]
Hm, I ran it on Intel PC under Ubuntu without any problems. Did not try to get it to work on pi (yet). 

 

 

vriendelijke groeten,

 

-/Peter Op de Beek
